insert into collection (collection_creator_id, collection_name) values (6, 'Maryland Hawkweed');
insert into collection (collection_creator_id, collection_name) values (7, 'Largeleaf Gypsoplaca Lichen');
insert into collection (collection_creator_id, collection_name) values (4, 'Blackthread Lichen');
insert into collection (collection_creator_id, collection_name) values (1, 'Lescuraea Moss');
insert into collection (collection_creator_id, collection_name) values (9, 'Erect Spiderling');
insert into collection (collection_creator_id, collection_name) values (6, 'Caralluma');
insert into collection (collection_creator_id, collection_name) values (5, 'Harvey''s Beaksedge');
insert into collection (collection_creator_id, collection_name) values (5, 'Sloane''s Tribisee');
insert into collection (collection_creator_id, collection_name) values (3, 'Huachuca Mountain Sedge');
insert into collection (collection_creator_id, collection_name) values (5, 'Torreya');
insert into collection (collection_creator_id, collection_name) values (8, 'Goldenrod');
insert into collection (collection_creator_id, collection_name) values (9, 'Pygmy Poppy');
insert into collection (collection_creator_id, collection_name) values (7, 'Pygmyflower Rockjasmine');
insert into collection (collection_creator_id, collection_name) values (2, 'Denseflower Indian Paintbrush');
insert into collection (collection_creator_id, collection_name) values (10, 'Sonoma Manzanita');
insert into collection (collection_creator_id, collection_name) values (1, 'Woodland Calamint');
insert into collection (collection_creator_id, collection_name) values (8, 'Western False Dragonhead');
insert into collection (collection_creator_id, collection_name) values (6, 'Alpine Bittercress');
insert into collection (collection_creator_id, collection_name) values (3, 'Hypnum Moss');
insert into collection (collection_creator_id, collection_name) values (3, 'Smotherweed');
insert into collection (collection_creator_id, collection_name) values (6, 'Carpon Desmodium');
insert into collection (collection_creator_id, collection_name) values (4, 'Seagrass');
insert into collection (collection_creator_id, collection_name) values (9, 'Thatching Grass');
insert into collection (collection_creator_id, collection_name) values (1, 'Siskiyou Bedstraw');
insert into collection (collection_creator_id, collection_name) values (8, 'Sargent''s Apple');
insert into collection (collection_creator_id, collection_name) values (6, 'San Clemente Island Milkvetch');
insert into collection (collection_creator_id, collection_name) values (9, 'Houghton''s Sedge');
insert into collection (collection_creator_id, collection_name) values (2, 'Mountain Soursop');
insert into collection (collection_creator_id, collection_name) values (2, 'Longhair Sedge');
insert into collection (collection_creator_id, collection_name) values (3, 'Dwarf Fireweed');
insert into collection (collection_creator_id, collection_name) values (2, 'Haleakala Stenogyne');
insert into collection (collection_creator_id, collection_name) values (7, 'Wild Quinine');
insert into collection (collection_creator_id, collection_name) values (6, 'Diverseleaf Crownbeard');
insert into collection (collection_creator_id, collection_name) values (10, 'White Ironbark');
insert into collection (collection_creator_id, collection_name) values (4, 'Lecidea Lichen');
insert into collection (collection_creator_id, collection_name) values (1, 'Schweinitz''s Waterweed');
insert into collection (collection_creator_id, collection_name) values (6, 'Hybrid Oak');
insert into collection (collection_creator_id, collection_name) values (4, 'Spotted Beebalm');
insert into collection (collection_creator_id, collection_name) values (7, 'Nevada Oryctes');
insert into collection (collection_creator_id, collection_name) values (5, 'Blindia Moss');
insert into collection (collection_creator_id, collection_name) values (2, 'Freycinetia');
insert into collection (collection_creator_id, collection_name) values (8, 'Rauiella Moss');
insert into collection (collection_creator_id, collection_name) values (10, 'Washington Beardtongue');
insert into collection (collection_creator_id, collection_name) values (4, 'Scaleseed');
insert into collection (collection_creator_id, collection_name) values (4, 'Prairie Flax');
insert into collection (collection_creator_id, collection_name) values (9, 'Slender Dwarf Morning-glory');
insert into collection (collection_creator_id, collection_name) values (1, 'Xanthoparmelia Lichen');
insert into collection (collection_creator_id, collection_name) values (6, 'Largeflower Suncup');
insert into collection (collection_creator_id, collection_name) values (6, 'Spiny Naiad');
insert into collection (collection_creator_id, collection_name) values (3, 'Asphodelus');
insert into collection (collection_creator_id, collection_name) values (1, 'Silveus'' Grass');
insert into collection (collection_creator_id, collection_name) values (2, 'Silky Lupine');
insert into collection (collection_creator_id, collection_name) values (10, 'Darnel Ryegrass');
insert into collection (collection_creator_id, collection_name) values (8, 'Running Clubmoss');
insert into collection (collection_creator_id, collection_name) values (7, 'Miracle Fruit');
insert into collection (collection_creator_id, collection_name) values (3, 'Domin''s Club');
insert into collection (collection_creator_id, collection_name) values (8, 'Guest Tree');
insert into collection (collection_creator_id, collection_name) values (3, 'Climbing False Buckwheat');
insert into collection (collection_creator_id, collection_name) values (1, 'Greene''s Maple');
insert into collection (collection_creator_id, collection_name) values (4, 'Thinleaf Creepingfern');
insert into collection (collection_creator_id, collection_name) values (1, 'Florida Skin Lichen');
insert into collection (collection_creator_id, collection_name) values (2, 'Michener''s Wart Lichen');
insert into collection (collection_creator_id, collection_name) values (7, 'Swamp White Oak');
insert into collection (collection_creator_id, collection_name) values (4, 'Lanceleaf Blanketflower');
insert into collection (collection_creator_id, collection_name) values (8, 'Darwin''s Berberis');
insert into collection (collection_creator_id, collection_name) values (6, 'Indian Warrior');
insert into collection (collection_creator_id, collection_name) values (4, 'Oldmaid');
insert into collection (collection_creator_id, collection_name) values (7, 'Erichsen''s Wart Lichen');
insert into collection (collection_creator_id, collection_name) values (6, 'Osterhout''s Lupine');
insert into collection (collection_creator_id, collection_name) values (1, 'Hairy Lipfern');
insert into collection (collection_creator_id, collection_name) values (6, 'Plantain Signalgrass');
insert into collection (collection_creator_id, collection_name) values (9, 'Hummock Honeymyrtle');
insert into collection (collection_creator_id, collection_name) values (1, 'Xylographa Lichen');
insert into collection (collection_creator_id, collection_name) values (10, 'Ridgetop Guavaberry');
insert into collection (collection_creator_id, collection_name) values (2, 'Hispaniolan Spleenwort');
insert into collection (collection_creator_id, collection_name) values (4, 'Illinois Pinweed');
insert into collection (collection_creator_id, collection_name) values (5, 'Latin Thorn-apple');
insert into collection (collection_creator_id, collection_name) values (5, 'Beard Lichen');
insert into collection (collection_creator_id, collection_name) values (6, 'Showy Gentian');
insert into collection (collection_creator_id, collection_name) values (10, 'Shield Lichen');
insert into collection (collection_creator_id, collection_name) values (7, 'Beard Lichen');
insert into collection (collection_creator_id, collection_name) values (9, 'Green Wattle');
insert into collection (collection_creator_id, collection_name) values (10, 'Arrowleaf Buckwheat');
insert into collection (collection_creator_id, collection_name) values (2, 'Bahama Nightshade');
insert into collection (collection_creator_id, collection_name) values (10, 'Peruvian Nightshade');
insert into collection (collection_creator_id, collection_name) values (5, 'Southern Arrowwood');
insert into collection (collection_creator_id, collection_name) values (3, 'Silver Cock''s Comb');
insert into collection (collection_creator_id, collection_name) values (2, 'Clubmoss');
insert into collection (collection_creator_id, collection_name) values (8, 'Scallion Grass');
insert into collection (collection_creator_id, collection_name) values (2, 'Kaiholena Cyanea');
insert into collection (collection_creator_id, collection_name) values (8, 'West Indian Woodsorrel');
insert into collection (collection_creator_id, collection_name) values (7, 'Florida Pineland Spurge');
insert into collection (collection_creator_id, collection_name) values (6, 'Flat-spiked Sedge');
insert into collection (collection_creator_id, collection_name) values (6, 'Allegheny Mountain Buttercup');
insert into collection (collection_creator_id, collection_name) values (6, 'Thinstem Lady''s Mantle');
insert into collection (collection_creator_id, collection_name) values (10, 'Skeletonleaf Willow');
insert into collection (collection_creator_id, collection_name) values (3, 'Malaysian Scurfpea');
insert into collection (collection_creator_id, collection_name) values (9, 'Awl-leaf Pearlwort');
insert into collection (collection_creator_id, collection_name) values (4, 'Hybrid Floatingheart');
insert into collection (collection_creator_id, collection_name) values (8, 'John Crownose');
